version: "3.8"

services:
  python:
    build:
      context: .
      args:
        APP_USER_ID: ${APP_USER_ID}
        APP_USER_NAME: ${APP_USER_NAME}
    volumes:
      - ../raspberry-pi-media-controller:/home/${APP_USER_NAME}/raspberry-pi-media-controller
    restart: unless-stopped